# Generated by Django 3.1.7 on 2021-02-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210220_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetailpage',
            name='article_summary',
            field=models.TextField(help_text='A short summary of your article', null=True),
        ),
    ]
