# Generated by Django 3.1.7 on 2021-02-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210223_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetailpage',
            name='date',
            field=models.DateField(null=True, verbose_name='Post date'),
        ),
    ]
