# Generated by Django 3.1.7 on 2021-03-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20210308_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleblogpage',
            name='author_name',
            field=models.CharField(help_text='Name of the writer of the article for home page', max_length=100, null=True),
        ),
    ]
