# Generated by Django 3.1.7 on 2021-03-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_articleblogpage_author_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleblogpage',
            name='author_name',
        ),
        migrations.AddField(
            model_name='blogdetailpage',
            name='author_name',
            field=models.CharField(help_text='Name of the writer of the article for home page', max_length=100, null=True),
        ),
    ]
