# Generated by Django 3.0.13 on 2021-06-02 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_auto_20210520_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogauthor',
            name='biographie',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
