# Generated by Django 3.0.13 on 2021-07-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0041_navbar_pagewithnavbar'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleblogpage',
            name='caption_intro_image',
            field=models.TextField(help_text='photo caption with  your © copyright', max_length=100, null=True),
        ),
    ]
