# Generated by Django 3.1.6 on 2021-02-20 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.ForeignKey(help_text='upload your logo here', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_logo', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Your logo',
                'verbose_name_plural': 'Your logos',
            },
        ),
    ]
