# Generated by Django 3.1.7 on 2021-03-07 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('menus', '0002_companylogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundMenuImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ForeignKey(help_text='Set the Background image of the menu ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'background image menu',
                'verbose_name_plural': 'background images menu',
            },
        ),
    ]
